// IOZEN LLVM IR Code Generator
// Generates LLVM IR from SSA IR for native code compilation

import { IRProgram, IRFunction, IRInstruction, IRValue } from '../ir';

export interface LLVMModule {
  functions: LLVMFunction[];
  globals: string[];
  declarations: string[];
}

export interface LLVMFunction {
  name: string;
  signature: string;
  body: string[];
}

export class LLVMGenerator {
  private tempCounter = 0;
  private labelCounter = 0;
  private currentFunction: IRFunction | null = null;
  private module: LLVMModule = {
    functions: [],
    globals: [],
    declarations: new Set<string>() as any
  };

  // Type mapping from IOZEN to LLVM
  private mapType(type: string): string {
    switch (type) {
      case 'number': return 'double';
      case 'string': return '%str';
      case 'bool': return 'i1';
      case 'void': return 'void';
      case 'ptr': return '%value*';
      default: return '%value*';
    }
  }

  newTemp(): string {
    return `%${this.tempCounter++}`;
  }

  newLabel(prefix = 'L'): string {
    return `${prefix}${this.labelCounter++}`;
  }

  generate(program: IRProgram): string {
    let output = '';
    
    // Type definitions
    output += '; IOZEN LLVM IR Module\n';
    output += '; Generated by IOZEN Compiler v2.0\n\n';
    
    // Opaque type for IOZEN values
    output += '%value = type opaque\n';
    output += '%str = type opaque\n\n';
    
    // External function declarations
    output += this.generateDeclarations();
    
    // Global variables (strings first, then globals)
    output += this.generateGlobals(program.globals, program.strings);
    
    // Functions
    for (const func of program.functions) {
      output += this.generateFunction(func);
    }
    
    return output;
  }

  private generateDeclarations(): string {
    let output = '';
    output += 'declare void @print_value(%value*)\n';
    output += 'declare void @print_string(%str*)\n';
    output += 'declare %value* @iozen_alloc()\n';
    output += 'declare %str* @iozen_string_new(i8*)\n';
    output += 'declare %value* @iozen_number_new(double)\n';
    output += 'declare %value* @iozen_bool_new(i1)\n';
    output += 'declare double @iozen_number_get(%value*)\n';
    output += 'declare i1 @iozen_bool_get(%value*)\n';
    output += 'declare %str* @iozen_string_get(%value*)\n';
    output += 'declare %value* @iozen_add(%value*, %value*)\n';
    output += 'declare %value* @iozen_sub(%value*, %value*)\n';
    output += 'declare %value* @iozen_mul(%value*, %value*)\n';
    output += 'declare %value* @iozen_div(%value*, %value*)\n';
    output += 'declare %value* @iozen_concat(%value*, %value*)\n';
    
    // Comparison operations
    output += 'declare i1 @iozen_eq(%value*, %value*)\n';
    output += 'declare i1 @iozen_ne(%value*, %value*)\n';
    output += 'declare i1 @iozen_lt(%value*, %value*)\n';
    output += 'declare i1 @iozen_le(%value*, %value*)\n';
    output += 'declare i1 @iozen_gt(%value*, %value*)\n';
    output += 'declare i1 @iozen_ge(%value*, %value*)\n';
    
    // Logical operations
    output += 'declare i1 @iozen_and(i1, i1)\n';
    output += 'declare i1 @iozen_or(i1, i1)\n';
    output += 'declare i1 @iozen_not(i1)\n';
    
    // Struct operations
    output += 'declare %value* @iozen_struct_get(%value*, i32)\n';
    output += 'declare void @iozen_struct_set(%value*, i32, %value*)\n';
    
    // Closure operations
    output += 'declare %value* @iozen_closure_new(%value*, %value*)\n';
    output += 'declare %value* @iozen_closure_get_func(%value*)\n';
    output += 'declare %value* @iozen_closure_get_env(%value*)\n';
    
    // Exception handling
    output += 'declare void @iozen_throw(%value*)\n';
    output += 'declare %value* @iozen_try_enter()\n';
    output += 'declare void @iozen_try_exit()\n';
    
    output += '\n';
    return output;
  }

  private generateGlobals(globals: Map<string, { type: string; init?: any }>, strings: Map<string, string>): string {
    let output = '';
    
    // String literals - move to before functions
    strings.forEach((value, key) => {
      const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
      output += `@.str.${key} = private unnamed_addr constant [${escaped.length + 1} x i8] c"${escaped}\\00"\n`;
    });
    
    if (strings.size > 0) {
      output += '\n';
    }
    return output;
  }

  private generateFunction(func: IRFunction): string {
    this.currentFunction = func;
    this.tempCounter = 0;
    this.labelCounter = 0;
    
    let output = '';
    
    // Function signature
    const returnType = func.returnType === 'void' ? 'void' : '%value*';
    const params = func.params.map(p => `%value*`).join(', ');
    output += `define ${returnType} @${func.name}(${params}) {\n`;
    
    // Entry block
    output += 'entry:\n';
    
    // Generate instructions
    const body = this.generateInstructions(func.instructions);
    output += body;
    
    output += '}\n\n';
    return output;
  }

  private generateInstructions(instructions: IRInstruction[]): string {
    let output = '';
    const labels = new Set<string>();
    
    // First pass: collect all labels
    for (const inst of instructions) {
      if (inst.op === 'label' && inst.label) {
        labels.add(inst.label);
      }
    }
    
    // Second pass: generate instructions
    let currentBlock = 'entry';
    for (const inst of instructions) {
      if (inst.op === 'label') {
        if (inst.label && !labels.has(inst.label + '_done')) {
          output += `${inst.label}:\n`;
          labels.add(inst.label + '_done');
        }
        continue;
      }
      
      output += `  ${this.generateInstruction(inst)}\n`;
    }
    
    return output;
  }

  private generateInstruction(inst: IRInstruction): string {
    switch (inst.op) {
      case 'const': {
        const dest = inst.dest || this.newTemp();
        const value = inst.src1 as IRValue;
        if (value.type === 'number') {
          return `${dest} = call %value* @iozen_number_new(double ${value.value})`;
        } else if (value.type === 'bool') {
          return `${dest} = call %value* @iozen_bool_new(i1 ${value.value ? 1 : 0})`;
        } else if (value.type === 'string') {
          return `${dest} = call %value* @iozen_string_new(i8* getelementptr inbounds ([${(value.value as string).length + 1} x i8], [${(value.value as string).length + 1} x i8]* @.str.${value.value}, i32 0, i32 0))`;
        }
        return `${dest} = call %value* @iozen_alloc()`;
      }
      
      case 'add': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_add(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'sub': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_sub(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'mul': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_mul(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'div': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_div(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'concat': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_concat(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      // Comparison operations
      case 'eq': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_eq(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'ne': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_ne(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'lt': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_lt(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'le': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_le(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'gt': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_gt(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'ge': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_ge(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      // Logical operations
      case 'and': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_and(i1 ${inst.src1}, i1 ${inst.src2})`;
      }
      
      case 'or': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_or(i1 ${inst.src1}, i1 ${inst.src2})`;
      }
      
      case 'not': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call i1 @iozen_not(i1 ${inst.src1})`;
      }
      
      // Struct field access
      case 'struct_get': {
        const dest = inst.dest || this.newTemp();
        const fieldIndex = inst.fieldIndex || 0;
        return `${dest} = call %value* @iozen_struct_get(%value* ${inst.src1}, i32 ${fieldIndex})`;
      }
      
      case 'struct_set': {
        const fieldIndex = inst.fieldIndex || 0;
        return `call void @iozen_struct_set(%value* ${inst.src1}, i32 ${fieldIndex}, %value* ${inst.src2})`;
      }
      
      // Closure operations
      case 'closure_new': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_closure_new(%value* ${inst.src1}, %value* ${inst.src2})`;
      }
      
      case 'closure_get_func': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_closure_get_func(%value* ${inst.src1})`;
      }
      
      case 'closure_get_env': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_closure_get_env(%value* ${inst.src1})`;
      }
      
      // Exception handling
      case 'throw': {
        return `call void @iozen_throw(%value* ${inst.src1})`;
      }
      
      case 'try_start': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_try_enter()`;
      }
      
      case 'try_end': {
        return `call void @iozen_try_exit()`;
      }
      
      case 'if': {
        // Conditional branch with proper condition
        const cond = inst.cond || inst.src1;
        return `br i1 ${cond}, label %${inst.label}, label %${inst.elseLabel || 'fallback'}`;
      }
      
      case 'print': {
        return `call void @print_value(%value* ${inst.src1})`;
      }
      
      case 'load': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = load %value*, %value** ${inst.src1}`;
      }
      
      case 'store': {
        return `store %value* ${inst.src2}, %value** ${inst.src1}`;
      }
      
      case 'var': {
        const dest = inst.dest || this.newTemp();
        return `${dest} = call %value* @iozen_alloc()`;
      }
      
      case 'call': {
        const dest = inst.dest ? `${inst.dest} = ` : '';
        const args = (inst.args || []).map(a => `%value* ${a}`).join(', ');
        return `${dest}call %value* @${inst.src1}(${args})`;
      }
      
      case 'ret': {
        if (inst.src1) {
          return `ret %value* ${inst.src1}`;
        }
        return 'ret void';
      }
      
      case 'goto': {
        return `br label %${inst.label}`;
      }
      
      default: {
        return `; TODO: ${inst.op} ${inst.comment || ''}`;
      }
    }
  }

  reset() {
    this.tempCounter = 0;
    this.labelCounter = 0;
    this.currentFunction = null;
    this.module = {
      functions: [],
      globals: [],
      declarations: new Set<string>() as any
    };
  }
}

export function createLLVMGenerator(): LLVMGenerator {
  return new LLVMGenerator();
}

export function generateLLVM(ir: IRProgram): string {
  const generator = createLLVMGenerator();
  return generator.generate(ir);
}
