// ============================================================
// IOZEN Language — SSA to C Code Generator
// Generates optimized C code from SSA IR
// ============================================================

import type {
  SSAModule,
  SSAFunction,
  SSABasicBlock,
  SSAInstruction,
  SSAValue,
} from './ssa_ir';
import { formatValue } from './ssa_ir';

/**
 * Phase 18: SSA-Based C Code Generator
 * 
 * Generates clean, optimized C code directly from SSA IR.
 * Benefits over AST-based codegen:
 * - Optimizations already applied (const prop, DCE)
 * - Phi nodes become simple variable assignments
 * - Dead code already eliminated
 * - Control flow is explicit
 */

export class SSACodeGenerator {
  private indent = '    ';
  private output: string[] = [];
  private currentFunction: SSAFunction | null = null;
  private blockOrder: string[] = [];
  private visitedBlocks = new Set<string>();

  generate(module: SSAModule): string {
    this.output = [];
    
    // Header
    this.emit('// Generated by IOZEN SSA Code Generator');
    this.emit('#include <stdio.h>');
    this.emit('#include <stdlib.h>');
    this.emit('#include <string.h>');
    this.emit('#include <stdbool.h>');
    this.emit('');
    
    // Generate each function
    for (const func of module.functions) {
      this.generateFunction(func);
      this.emit('');
    }
    
    return this.output.join('\n');
  }

  private generateFunction(func: SSAFunction): void {
    this.currentFunction = func;
    this.visitedBlocks.clear();
    this.blockOrder = [];
    
    // Calculate block order (simple DFS)
    this.calculateBlockOrder(func.entryBlock);
    
    // Function signature
    const params = func.params.map(p => `int ${p.name}_${p.initialVersion}`).join(', ');
    this.emit(`int ${func.name}(${params}) {`);
    
    // Generate variable declarations
    this.generateVariableDeclarations(func);
    
    // Generate blocks
    for (const blockId of this.blockOrder) {
      const block = func.blocks.get(blockId);
      if (block) {
        this.generateBlock(block);
      }
    }
    
    this.emit('}');
  }

  private calculateBlockOrder(startBlock: string): void {
    const stack = [startBlock];
    
    while (stack.length > 0) {
      const blockId = stack.pop()!;
      
      if (this.visitedBlocks.has(blockId)) {
        continue;
      }
      
      this.visitedBlocks.add(blockId);
      this.blockOrder.push(blockId);
      
      const block = this.currentFunction!.blocks.get(blockId);
      if (!block) continue;
      
      // Add successors based on terminator
      const term = block.terminator;
      if (term.kind === 'branch') {
        // Visit false block first (so it appears after true block)
        stack.push(term.falseBlock);
        stack.push(term.trueBlock);
      } else if (term.kind === 'jump') {
        stack.push(term.target);
      }
    }
  }

  private generateVariableDeclarations(func: SSAFunction): void {
    const declaredVars = new Set<string>();
    
    // Collect all variables that need declaration
    for (const [_, block] of func.blocks) {
      for (const inst of block.instructions) {
        const dest = this.getDestVar(inst);
        if (dest && !declaredVars.has(dest)) {
          declaredVars.add(dest);
        }
      }
    }
    
    // Emit declarations
    if (declaredVars.size > 0) {
      const vars = Array.from(declaredVars).sort();
      for (const v of vars) {
        this.emit(`${this.indent}int ${v};`);
      }
    }
  }

  private generateBlock(block: SSABasicBlock): void {
    // Label (except for entry block)
    if (block.id !== this.currentFunction!.entryBlock) {
      this.emit(`${block.id}:`);
    }
    
    // Instructions
    for (const inst of block.instructions) {
      this.generateInstruction(inst);
    }
    
    // Terminator
    this.generateTerminator(block.terminator);
  }

  private generateInstruction(inst: SSAInstruction): void {
    switch (inst.kind) {
      case 'assign': {
        const src = this.valueToC(inst.src);
        this.emit(`${this.indent}${inst.dest}_${inst.destVer} = ${src};`);
        break;
      }
      
      case 'binary': {
        const left = this.valueToC(inst.left);
        const right = this.valueToC(inst.right);
        const op = this.operatorToC(inst.op);
        this.emit(`${this.indent}${inst.dest}_${inst.destVer} = ${left} ${op} ${right};`);
        break;
      }
      
      case 'unary': {
        const operand = this.valueToC(inst.operand);
        const op = inst.op === 'not' ? '!' : inst.op;
        this.emit(`${this.indent}${inst.dest}_${inst.destVer} = ${op}${operand};`);
        break;
      }
      
      case 'call': {
        const args = inst.args.map(a => this.valueToC(a)).join(', ');
        this.emit(`${this.indent}${inst.dest}_${inst.destVer} = ${inst.func}(${args});`);
        break;
      }
      
      case 'phi': {
        // Phi nodes are handled specially
        // In C, we emit phi as assignments from predecessors
        // For the first predecessor, assign directly
        // For subsequent ones, this would need to be at predecessor end
        // For simplicity, we emit as a comment showing the phi
        const incoming = inst.incoming.map(i => 
          `${this.valueToC(i.value)} /* from ${i.block} */`
        ).join(', ');
        
        // For code generation, phi nodes need special handling
        // We emit a comment and the first incoming value
        // (In a real implementation, this would be split across predecessors)
        if (inst.incoming.length > 0) {
          this.emit(`${this.indent}// phi: ${inst.dest}_${inst.destVer} = ${incoming}`);
          this.emit(`${this.indent}${inst.dest}_${inst.destVer} = ${this.valueToC(inst.incoming[0].value)};`);
        }
        break;
      }
      
      case 'index_load': {
        const arr = this.valueToC(inst.array);
        const idx = this.valueToC(inst.index);
        this.emit(`${this.indent}${inst.dest}_${inst.destVer} = ${arr}[${idx}];`);
        break;
      }
      
      case 'index_store': {
        const arr = this.valueToC(inst.array);
        const idx = this.valueToC(inst.index);
        const val = this.valueToC(inst.value);
        this.emit(`${this.indent}${arr}[${idx}] = ${val};`);
        break;
      }
    }
  }

  private generateTerminator(terminator: SSABasicBlock['terminator']): void {
    switch (terminator.kind) {
      case 'return': {
        const value = terminator.value ? this.valueToC(terminator.value) : '0';
        this.emit(`${this.indent}return ${value};`);
        break;
      }
      
      case 'branch': {
        const cond = this.valueToC(terminator.cond);
        this.emit(`${this.indent}if (${cond}) {`);
        this.emit(`${this.indent}${this.indent}goto ${terminator.trueBlock};`);
        this.emit(`${this.indent}} else {`);
        this.emit(`${this.indent}${this.indent}goto ${terminator.falseBlock};`);
        this.emit(`${this.indent}}`);
        break;
      }
      
      case 'jump': {
        this.emit(`${this.indent}goto ${terminator.target};`);
        break;
      }
      
      case 'exit': {
        // No code for exit
        break;
      }
    }
  }

  private valueToC(value: SSAValue): string {
    switch (value.kind) {
      case 'constant':
        if (typeof value.value === 'string') {
          return JSON.stringify(value.value);
        }
        if (typeof value.value === 'boolean') {
          return value.value ? '1' : '0';
        }
        if (value.value === null) {
          return '0';
        }
        return String(value.value);
      
      case 'variable':
        return `${value.name}_${value.version}`;
      
      case 'undefined':
        return '0';
      
      default:
        return '0';
    }
  }

  private operatorToC(op: string): string {
    const opMap: Record<string, string> = {
      'and': '&&',
      'or': '||',
      '==': '==',
      '!=': '!=',
      '<': '<',
      '>': '>',
      '<=': '<=',
      '>=': '>=',
      '+': '+',
      '-': '-',
      '*': '*',
      '/': '/',
      '%': '%',
    };
    return opMap[op] || op;
  }

  private getDestVar(inst: SSAInstruction): string | null {
    switch (inst.kind) {
      case 'assign':
      case 'binary':
      case 'unary':
      case 'call':
      case 'phi':
      case 'index_load':
      case 'field_load':
        return `${inst.dest}_${inst.destVer}`;
      default:
        return null;
    }
  }

  private emit(line: string): void {
    this.output.push(line);
  }
}

export function generateCFromSSA(module: SSAModule): string {
  const generator = new SSACodeGenerator();
  return generator.generate(module);
}
